# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
    checkLatest: true
    
- task: CmdLine@2
  inputs:
    script: 'npm i && npm run ng-lint && ls -la'

- task: publishhtmlreport@1
  inputs:
    htmlType: 'genericHTML'
    htmlPath: '$(Build.SourcesDirectory)/ng-lint-report/report.html'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'cloud_orchestrator_ui_v2'
    cliSources: '.'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

- task: SonarQubeAnalyze@5
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  
- task: DockerCompose@0
  displayName: Docker Build
  inputs:
    action: Build services
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'docker-hub'
    dockerComposeFile: '**/docker-compose.yml'
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    dockerComposeFileArgs: |
        TAG=${{ variables['Build.BuildId'] }}
        REGISTRY=ganeshpote1988

- task: DockerCompose@0
  displayName: Docker Push
  inputs:
    action: Push services
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'docker-hub'
    dockerComposeFile: '**/docker-compose.yml'
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    dockerComposeFileArgs: |
        TAG=${{ variables['Build.BuildId'] }}
        REGISTRY=ganeshpote1988
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')